
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint.health.show-details: always


spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 106.10.54.127

